### ISSUE TITLE
Bad encodings

### ISSUE THREAD

**Issue by dsl** [duplicati/duplicati#1241]
When duplicati on linux hits files with 'interesting' non-ascii filenames, it outputs the following:

FindNextFile: Bad encoding for '/my/file/name.png'
Consider using MONO_EXTERNAL_ENCODINGS

Running ls -l /my/file/ gives:
?????name.png

It's not clear whether this is a warning, or a failure to back up, so it'd be good to make the message clearer, plus ideally fix the problem with processing non-ascii filenames.
##

**Comment by kenkendk** [comment]
I have this issue as well. The error message is not from Duplicati, but from Mono:
http://www.mono-project.com/docs/faq/technical/#monoexternalencodings

The description does not state what happens to the files that cannot be decoded:
```
MONO_EXTERNAL_ENCODINGS
              If set, contains a colon-separated list of text encodings to try when turning externally-generated text (e.g. command-line arguments or filenames) into Unicode.  The encoding names come from  the
              list provided by iconv, and the special case "default_locale" which refers to the current locale's default encoding.

              When reading externally-generated text strings UTF-8 is tried first, and then this list is tried in order with the first successful conversion ending the search.  When writing external text (e.g.
              new filenames or arguments to new processes) the first item in this list is used, or UTF-8 if the environment variable is not set.

              The problem with using MONO_EXTERNAL_ENCODINGS to process your files is that it results in a problem: although its possible to get the right file name it is not necessarily possible to  open  the
              file.  In general if you have problems with encodings in your filenames you should use the "convmv" program.
```

**Comment by crazy4chrissi** [comment]
Almost the same issue for me on a Debian Wheezy system, the error is only slightly different:
```
mono_w32file_find_next: Bad encoding for '/[...]/Bl�serklasse.JPG' 
Consider using MONO_EXTERNAL_ENCODINGS
```
mono --version returns:
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)

Once the backup ran through, I will check whether this file can be restored from the backup.

**Comment by rsteckler** [comment]
@crazy4chrissi Any uppdate?  Were you able to restore the file successfully?

**Comment by meersjo** [comment]
Reporting in with same issue.

The general solution is using convmv to rename your files to the proper (utf8) encoding, as they likely originate on a windows or other system and haven't been translated properly.

Try this loop if you're unsure what the source encoding is (convmv is default noop, but do verify that in your own install):
> for x in `convmv --list`; do
>   echo "### $x";
>   yes n | convmv -f $x -t utf16 "`ls Hanahira\!\ \(* | head -n 1`";
> done

This is, however, not always the solution - my problem with specific files from PlayOnLinux isn't solved by this: none of the results seem OK...

Backup is still running, so don't know if files will be restoreable yet.

**Comment by meersjo** [comment]
As I kind of expected, the files are not in the completed backup - if the filename can't be decoded properly, it can also not be used to open the file...

I'm not quite sure this is strictly a Duplicati problem, though - the cause is the underlying bad filenames.

Incidentally I've seen similar issues with TSM backups; the resolution there was either to properly name the files, or in our particular case (backup of a cifs share) start the backup software in a session with an appropriate locale set.

**Comment by ajkessel** [comment]
Same issue here. This is an ext3 filesystem that is synced with an NTFS drive elsewhere, thus the filename encoding clash. But I can read and manipulate the files without problem on the Linux box--shouldn't there be either a Duplicati or Mono fix so the files get backed up without extensive manual correction? Seems like a lot of risk to put on the user to have to be monitoring filenames that are otherwise read without problem by the OS.

**Comment by meersjo** [comment]
For external mounts, I kind of feel that it's the mount helper's responsibility to translate between encodings, although on the other hand, the remote encoding could be a superset of the local encoding, making one-to-one translation impossible...

**Comment by vascotenner** [comment]
Is there any update on this issue? It still persists. Many other programs running on this linux system do not have issues with such filenames like ```Financi�n.pdf```

**Comment by digulla** [comment]
Still happens with 2.0.5.1.

To test this, you can create a file `Umlautsöäü` with ISO-8859-1 encoding like so:

    touch $'Umlauts\xf6\xe4\xfc'

([BASH syntax](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html#ANSI_002dC-Quoting)).

**Comment by warwickmm** [comment]
Confirmed that there are issues backing up a file created by
```
touch $'Umlauts\xf6\xe4\xfc'
```
with version 2.0.5.110 and 6.10.0.

**Comment by kenkendk** [comment]
Closing this as Duplicati is no longer using Mono
