### ISSUE TITLE
Missing XSRF Token and other GUI problems

### ISSUE THREAD

**Issue by VidalDuval** [duplicati/duplicati#1319]
I'm using Duplicati 2 on Linux Mint 17.1. Since the last update (march 5), I can't perform any action in the GUI without a popup saying "Missing XSRF Token". Also, the GUI is constantly reloading, unresponsive or blank. Often I see a glimpse of the "Server connection lost" window before the screen turns blank, even though the server seems to be running. My scheduled backups (to a local server over SSH) ran last night in spite of this.

Thanks!

**Comment by kenkendk** [comment]
A related report is here:
https://groups.google.com/forum/m/#!topic/duplicati/MPdgj_sWsJU

I have been debugging this, but the problem never occurs on my setups.
I have tested with Firefox, Chrome, Internet Explorer on OSX and Windows, but never see the issue.

The reloading happens because the error is detected, and should be solved by reloading the page, as that will produce a new XSRF token.

Do you have any plugins or similar that could be suspected of changing the headers?

Which browser are you using?

**Comment by VidalDuval** [comment]
Thanks for the reply. I'm using Chromium 40.0.2214.111. I disabled all the installed extensions but the problem was still present. I also tried using Firefox 36 and Opera 12.16 with the same results.

I tried reverting to the last working version by copying the content of the "2.0.0.82" folder found in the "updates" folder and using this new folder to execute Duplicati. Unfortunatley, the same errors occured. Is there a better way to revert or is there a problem in the config folder (~/.config/Duplicati/ on my system)?

**Comment by renestach** [comment]
You can switch back to older versions by modifying the content of the file updates/current

2.0.0.82 can be found here: http://updates.duplicati.com/preview/duplicati-2.0.0.82_preview_2015-02-15.zip

**Comment by VidalDuval** [comment]
Thank you @renestach for the tip, it worked perfectly. I'll stay with that version until a fix is found. Let me know if I can provide information to help.

**Comment by renestach** [comment]
Are you running any kind of local proxy or ad blocker or anything outside the browsers? As all browsers are failing, I assume that there is a network tool that is modifying the data. Anything?

**Comment by VidalDuval** [comment]
Not that I know of... maybe something installed by default but I doubt it.

**Comment by sporkhub** [comment]
I have the same issue.  If it helps, here are the headers for one of the requests that failed.  Each request, including static css, js, and images set a new xsrf cookie.  The special characters that get url encoded seem suspicious.  Could be a red herring, but perhaps hex rather than base64 would work better?

GET http://127.0.0.1:8200/control.cgi?action=system-info HTTP/1.1
Host: 127.0.0.1:8200
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-XSRF-Token: 0C+47p1fuDYKigR5YlZ/nTXCQphWWEDp5SBjPohhPVE=
X-Requested-With: XMLHttpRequest
Referer: http://127.0.0.1:8200/greeno/
Cookie: xsrf-token=0C%2B47p1fuDYKigR5YlZ%2FnTXCQphWWEDp5SBjPohhPVE%3D
Connection: keep-alive


HTTP/1.1 400 Missing XSRF Token
Date: Sat, 07 Mar 2015 03:15:20 GMT
Content-Length: 0
Content-Type: 
Server: Tiny WebServer
Connection: close
Set-Cookie: xsrf-token=fZ9g2s%2FFjerHqXbnfflrQCCgeCga8fmS2c%2BgRap%2FC9c%3D; expires=Sat, 07 Mar 2015 03:25:20 GMT;path=/;

**Comment by sporkhub** [comment]
The encoding was (probably) a red herring.  Having nothing better to do on a Friday night I brought this up locally in a debugger.

The problem is that you're mixing DateTime.Now and DateTime.UtcNow when computing expiration for xsrf tokens in AuthenticationHandler.HasXSRFCookie().  I guess you must be in a timezone that currently overlaps with UTC, whereas those of us on this bug aren't.

Also, since I was in the code, you may have synchronization issues around your dictionaries in that same class.  I'm not sure what your threading model is, but while I was debugging it looked like multiple threads might be accessing m_activexsrf at the same time.

**Comment by kenkendk** [comment]
Yes, that explains why I could not reproduce. Thanks for finding this.

The concurrent access is made in such a way that it is thread-safe without using locks.

The basic idea is that all operations on the dictionary are thread-safe, except iteration.
When using the dictionary, the actual items are extracted with TryGet, such that it does not matter if there is a race. When deleting, the tokens are converted to a list to work around the problem with iteration.

**Comment by sporkhub** [comment]
The fix in 2.0.0.85 works for me, thanks!

Also, thanks for the explanation on the dictionary synchronization.  This is what happens when a Java developer attempts to read C# code by pretending it's Java :)

**Comment by VidalDuval** [comment]
The fix is working fine. As a side note, I had to set my clock to UTC to download and install the update from the web interface.

Thanks to all :)

**Comment by akirayamamoto** [comment]
I still have this problem... https://www.whatismybrowser.com/w/HPZ54LQ
'You are currently running Duplicati - 2.0.2.1_beta_2017-08-0'

**Comment by j710** [comment]
@akirayamamoto Me too, turned off user agent spoofing in uMatrix and it appears to be better. No idea if that's credible or if you have that going on...

**Comment by Pafzedog** [comment]
Same for me here
Gnu/linux Ubuntu 17.10
Firefox Nightly 57
Duplicati 2.0.2.1_beta_2017-08-01

**Comment by MatejKovacic** [comment]
The same problem here - 2.0.2.1_beta_2017-08-01 on Ubuntu Zesty (17.04) and Firefox 55.0.2 (64-bit).

**Comment by jorisvandesande** [comment]
I have the same issue on my Synology NAS with version 2.0.2.1_beta_2017-08-01. In Firefox 54.0.1.

**Comment by daylightbrightledlight** [comment]
I also have this issue with Duplicati  2.0.2.1_beta_2017-08-01 on macOS 10.12 with Google Chrome 60.0.3112.113.

We should reopen this issue.

**Comment by TheoRatliff** [comment]
Yep, this issue still exists.

duplicati-2.0.2.1_beta_2017-08-01-x64
Win10 x64 1503.540
Chrome 60.0.3112.113

**Comment by martinr63** [comment]
Today I had this issue after booting with empty cmos battery.

duplicati-2.0.1.73_experimental_2017-07-15-x64
Win10
Version 60.0.3112.113 (Offizieller Build) (64-Bit)

**Comment by mjeltsch** [comment]
Same here today: On Ubuntu 16.04. 2.0.2.1_beta_2017-08-01
Upon the first run: "Error Missing XRSF token"

**Comment by meersjo** [comment]
Just had this on a testing setup in virtualbox; haven't seen it yet on my actually-used install on my laptop. Bug #2635 seems to be both relevant and maybe a good master for this, as @kenkendk seems to actually know the cause :-p

**Comment by ajaymdesai** [comment]
I keep getting this on first load. Ubuntu 16.04 2.0.2.1_beta_2017-08-01

**Comment by SeBsZ** [comment]
Keep getting this message on Windows 2.0.2.1_beta_2017-08-01 when I double click the system tray icon to get to the Web UI. Doesn't happen every time though.
