### ISSUE TITLE
Restore of backup from scratch from gdrive fails

### ISSUE THREAD

**Issue by gfullmer** [duplicati/duplicati#1437]
1. I lost a disk drive recently with the upgrade to Windows 10. Long story :-(
2. I previously did a full backup using duplicati on gdrive with a passphrase with version 2.0
3. Tried to do a restore from backup and got the message:
The page 127.0.0.1:8200 Says:
Failed to get list of backup times:
No filesets found on remote target

I currently have Duplicati 2.0.0.87- 2.0.0.87_preview_2015-07-03 installed.

4. I downloaded the files off of my gdrive (over 2 gigs) and dycrypted them using acscrypt with the old passphrase.  That worked OK.  However, when I try to get a list of the files with either the gui or command line I get the same "No filesets found on remote target".

5.  Followed the instructions to delete the local database (.sqlite files in the local AppData directory) and tried to do a rebuild of the local database which went OK without messages However, I still get the same message when I try to get it from either the local non-encrypted or encrypted repository and also the remote gdrive repository.

I really appreciate the work the developers have put into this product and was hoping not having to go to a commercial or open (non-encrypted) repository.  Any help would be appreciated.

Thanks,
Glen

**Comment by kenkendk** [comment]
I can see others report the same issues, and I suspect that the UI has a bug. Can you try to do this on the commandline?

To build a local database do this:
```Duplicati.CommandLine.exe repair file://c:\backupdata --dbpath=c:\db.sqlite --no-encryption```

This should give you a database file you can open with an SQLite editor, to verify that the files are actually there.

Then list versions:
```Duplicati.CommandLine.exe list file://c:\backupdata --dbpath=c:\db.sqlite --no-encryption```

And finally restore:
```Duplicati.CommandLine.exe restore file://c:\backupdata --dbpath=c:\db.sqlite --no-encryption --restore-target=c:\restored --version=0```

**Comment by gfullmer** [comment]
Thanks Ken, for the quick response.

C:\Users\Glen\Duplicati>Duplicati.CommandLine.exe repair file://c:\users\Glen\Downloads\Dell2NoPass --dbpath=c:\users\Glen\db.sqlite --no-encryption

Here is the response I got doing it with the decrypted directory

  Listing remote folder ...
remote file duplicati-i0b80c3dd53ab47ec966bcd7d12548929.dindex.zip.aes is listed as Verified with size 217 but should be 32653, please verify the sha256 hash "QncSEGr4Wv1SjWC3K2hGoN9pb4jyuXNoR1WxxKSDNvM="
remote file duplicati-i0f626ed7bd2b4e77b62b2e2f19edb691.dindex.zip.aes is listed as Verified with size 217 but should be 61453, please verify the sha256 hash 
================================================
..... with many more with the same above type messages.
================================================

  Downloading file (unknown) ...
Sucessfully captured hash for duplicati-i0b80c3dd53ab47ec966bcd7d12548929.dindex.zip.aes, updating database
  Downloading file (unknown) ...
Sucessfully captured hash for duplicati-i0f626ed7bd2b4e77b62b2e2f19edb691.dindex.zip.aes, updating database
  Downloading file (unknown) ...
Sucessfully captured hash for duplicati-i25bfc7971d5b44819d76f21a9c4a97e3.dindex.zip.aes, updating database
  Downloading file (unknown) ...
Sucessfully captured hash for duplicati-i276e1f650dad4ddb8e8465052d900a8e.dindex.zip.aes, updating database

======================================================
... above repeating may times
======================================================

Failed to perform cleanup for missing file: duplicati-20150726T202359Z.dlist.zip.aes, message: No such remote file: duplicati-20150726T202359Z.dlist.zip.aes => No such remote file: duplicati-20150726T202359Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150727T200001Z.dlist.zip.aes, message: No such remote file: duplicati-20150727T200001Z.dlist.zip.aes => No such remote file: duplicati-20150727T200001Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150728T200000Z.dlist.zip.aes, message: No such remote file: duplicati-20150728T200000Z.dlist.zip.aes => No such remote file: duplicati-20150728T200000Z.dlist.zip.aes

======================================================
... above repeating may times
======================================================

Failed to perform cleanup for missing file: duplicati-20150729T200000Z.dlist.zip.aes, message: No such remote file: duplicati-20150729T200000Z.dlist.zip.aes => No such remote file: duplicati-20150729T200000Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150802T173952Z.dlist.zip.aes, message: No such remote file: duplicati-20150802T173952Z.dlist.zip.aes => No such remote file: duplicati-20150802T173952Z.dlist.zip.aes

======================================================
... above repeating may times
======================================================

Failed to perform cleanup for missing file: duplicati-20150803T080000Z.dlist.zip.aes, message: No such remote file: duplicati-20150803T080000Z.dlist.zip.aes => No such remote file: duplicati-20150803T080000Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150804T080000Z.dlist.zip.aes, message: No such remote file: duplicati-20150804T080000Z.dlist.zip.aes => No such remote file: duplicati-20150804T080000Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150805T080000Z.dlist.zip.aes, message: No such remote file: duplicati-20150805T080000Z.dlist.zip.aes => No such remote file: duplicati-20150805T080000Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-20150806T080000Z.dlist.zip.aes, message: No such remote file: duplicati-20150806T080000Z.dlist.zip.aes => No such remote file: duplicati-20150806T080000Z.dlist.zip.aes
Failed to perform cleanup for missing file: duplicati-b0753f4ad9875462fb3389cc405b9363a.dblock.zip.aes, message: Unexpected empty block volume: duplicati-b0753f4ad9875462fb3389cc405b9363a.dblock.zip.aes => Unexpected empty block volume: duplicati-b0753f4ad9875462fb3389cc405b9363a.dblock.zip.aes

======================================================
... above repeating may times
======================================================

Then running:

C:\Users\Glen\Duplicati>Duplicati.CommandLine.exe list file://c:\users\Glen\Downloads\Dell2NoPass --dbpath=c:\users\Glen\db.sqlite --no-encryption 

I get:

No time or version matched a fileset

===================
same message as before from the UI
===================

When I do it on the encrypted downloaded gdrive directory (after doing an unzip) with:

Duplicati.CommandLine.exe repair file://c:\users\Glen\Downloads\Dell2 --dbpath=c:\users\Glen\db.sqlite

it gave me:

Enter encryption passphrase: ********
  Listing remote folder ...
  Downloading file (31.89 KB) ...
  Downloading file (60.01 KB) ...
  Downloading file (29.31 KB) ...
Failed to process index file: duplicati-i0f626ed7bd2b4e77b62b2e2f19edb691.dindex.zip.aes => Unexpected number of remote volumes detected: 0!
  Downloading file (163.23 KB) ...
  Downloading file (57.29 KB) ...
  Downloading file (372.31 KB) ...
Failed to process index file: duplicati-i2da8f0dd6ffb4136b6d05c158b97c9d6.dindex.zip.aes => Unexpected number of remote volumes detected: 0!
  Downloading file (33.86 KB) ...
======================================================
... above repeating may times
======================================================

Then doing:

Duplicati.CommandLine.exe list file://c:\users\Glen\Downloads\Dell2 --dbpath=c:\users\Glen\db.sqlite

I get:

No time or version matched a fileset
----------------------------------------------
Argh!  ;-)

Thanks again for looking into this,  Any other suggestions?
Glen

**Comment by gfullmer** [comment]
I would be more than happy to recover any files.  I can decrypt and unzip them, but is there a way without Duplicati to put any of them back together?

**Comment by gfullmer** [comment]
I know that some of the files are there as I can take a non-encrypted repository and unzip the files and can edit a file and recognize the file as a PDF or text file.  That is hit and miss and of course I don't know the name of the file nor its location in the repository, but at least it is letting me know that there are files out there.  Questions:

Can one restore it manually with file operations?  I have access to a Linux machine and its commands.  

I noticed that there are files in the vol directory that are still encrypted.  I think they come from the index zip files.  I tried to decrypt them using the previous used passcode to no avail.  I noticed that the process that you advised gave error messages that it failed to process the index file for that reason?  Is there a way around that?

Thanks,
Glen

**Comment by kenkendk** [comment]
For the repair process, make sure --dbpath points to a non-existing file.
It looks like you have an existing database that nows about the files ending in .aes.
Those files should not be there if you decrypted (the file extensions should not be .aes).

For manual restore, I have registered issue #1439 to assist in that.

To restore a single file, you need to pick a dlist file. The filename is a timestamp, so you may want to most recent file. Inside the zip file, you will find a json file with the name of all files.

For small files (less than --block-size, default 10kb) you simply take the file hash. Then search in all the dblock archives files for a file with that name, and copy it to the desired name.

For larger files (more than --block-size), you see a list of blocklisthashes attached to the filename. Locate each blocklisthash in turn, by searching the dblock archives for a file with that name. Each of these files contains a list of hashes, binary encoded (i.e. each 32 bytes is a hash). Concatenate all found hashes. You should get a list like: [blocklisthash1_hash1, blocklisthash1_hash2, ..., blocklisthash2_hash1, blocklisthash2_hash2, ...].

For each hash in the list, locate the file in the dblock archive that has that name, and append it to the desired target file.

After restoring the file, you can check the entire file hash from the dlist file.

**Comment by gfullmer** [comment]
Hello Kenneth,

I did make sure that the --dbpath points to a non-existing file.  However, I think I have might have found the problem - some process has renamed a file in the duplicatixxxx.dindex\vol and given it an .aes extension.  In the .dindex\vol directory I have only that renamed file.  However, if I change the name of it (getting rid of the .aes) and edit it, I find that it is not encrypted and looks something like:

{"blocks":[{"hash":"LVQVGKdE1DOGuYw/bxRhgvGLFr6w76E/KCMpcQIrOLw=","size":102400},{"hash":"uRdIB0yOihpxJ5qISFmhAuvn6v/6zveXj7WvCzSka/0=","size":102400},{"hash":"VWfAEcx6qVotCDtv8yTyl+P+to2sJZAaANMYS3gJlS0=","size":102400},{"hash":"VHpP5drRtSCSbsDk0Fj1JbbKZ/Mm+PooWSywRs/7CM8=","size":102400},{"hash":"djqG8/w66uTsN+kEtHrIwabqd5aRV9z4eRyaroUSrvs=","size":102400}...

Which looks like the block hash table.  What should it be called?  By what naming convention?

If I change all of these files in the .dindex/vol to their appropriate name, and rerun restore, do you think it might work?  

Not sure who/what put that .aes extension on the file.

Again thanks for your answer and all the work the developers do in creating this product,
Glen

**Comment by gfullmer** [comment]
Created another backup with one directory and one file with the web-based GUI.  When restoring it fails the same way as before:  

The page at 127.0.0.1:8200 says:
Failed to get list of backup times:
No filesets found on remote target

At first I thought it was Windows 10 firewall, but I turned it off with the same results.

If you are running Duplicati with Windows 10 with gdrive, make sure that a simple backup works.

Kenneth, any suggestions on what I should look at now?

**Comment by gfullmer** [comment]
Also, went over to a Linux machine and installed Duplicati and had the issue documented at:

https://github.com/duplicati/duplicati/issues/1211

Did the same experiment under Kubuntu that I did under Windows 10 (creating a simple non-encrypted backup and trying to restore it) and got the same message.  The backup seems to work OK.  Got the files on gdrive, but restore failed.

**Comment by gfullmer** [comment]
Did the simple experiment again with web GUI under Windows 10 and did "Restore Files..." from the pull down next to the Repository name instead of the "Restore from target" pull down and it worked and gave me a list of files.  However, doing a "Restore from target" gives me "Failed to get list of backup times:" message again, even when using the same backup name and remote name.  Aren't they the same given the same backup name? Should they be different? If so, how?

Obviously losing the disk I don't have the original backup name unlike when I did the above test.  Am I missing something here?

Also I noticed in the hash name in the filelist.json file is different than the file name in the repository.  Looks like all "/" characters have been changed to "_".  Was that for Unix vs Windows compatibility?  Or something else?

Thanks again, 
Glen

**Comment by kenkendk** [comment]
When it fails, I recommend using the commandline. The GUI hides things that are meant to simplify the experience, but that makes it hard to find errors.

The dindex files should be called "duplicati-ixxxx.dindex.zip" if they are not encrypted. It looks like the file is not compressed either. It should be a zip-compressed file.

The changes with / and + prevent clashes with filenames. It is the "URL safe" version of Base64 encoding, listed as base64url:
https://en.wikipedia.org/wiki/Base64#Implementations_and_history

**Comment by gfullmer** [comment]
OK.  Here is what I did with my simple example after I found it worked with the GUI. 

1. I downloaded it from gdrive which downloads one zip file.  I unzip it into a directory. 
2. In that directory are two dlist.zip.aes files, two dblocks.zip.aes, and two dindex.zip.aes files ( I had previously done one update on this backup test)
3. I run decrypt on all of the files in the directory (Fin5) and delete the .aes files so I only have zip files.
4. I run Duplicati.CommandLine.exe repair (see screenshot below) and get error messages. I deleted the db.sqlite file.
![fullscreen capture 8182015 100023 am bmp](https://cloud.githubusercontent.com/assets/1638596/9337301/70a5ae94-4593-11e5-8f56-4d14e6617b42.jpg)

5. I run Duplicati.CommandLine.exe list and get "no time or version match a file set" message.
6. I run the GUI from the gdrive encrypted repository and it seems to be working OK.  (see screenshot)

![fullscreen capture 8182015 100748 am bmp](https://cloud.githubusercontent.com/assets/1638596/9337314/7c33403c-4593-11e5-8889-b18bf2dbf507.jpg)


Am I missing something here?

Thanks for all you do, Kenneth, and for your response.

**Comment by gfullmer** [comment]
From your instructions I am not sure how to restore a file that is greater than --blocksize from a corrupted backup.

In which file do I see a list of "blocklisthashes attached to the filename"?
Not sure how to go to a blocklisthashes to a list of files to concatenate and then to the final file? 

Would you please walk through that with tools that are on windows or can be downloaded for windows?  Thanks.

**Comment by kenkendk** [comment]
Is there anything sensitive or private in your data? Could you send med the zip so I can try it?

You see the blocklisthashes in the dlist file.

There are no tools that I am aware of that can do the restore.

**Comment by gfullmer** [comment]
When I mentioned restore, I meant from scratch.  How can I do it specifically in Windows or Linux with more specificity?  How would you do it?

There is no sensitive data in the example so I am emailing you its decrypted zip file. Let me know if you don't get it.

Thanks again for looking at it.

**Comment by gfullmer** [comment]
Every 32 bits in the blocklisthashes file references a file hash, OK.  Found the file that has those blocklisthashes for the file I want to restore. What function might one use to that given a 32 bit sequence in that file to get a file hash tag? I guess I could look at the code to see how it is done, but thought I would ask you.  Again, thanks for all your help.

**Comment by kenkendk** [comment]
I have now added the recovery tool to source, and expect to make a new build shortly.

The 32 bytes are simply base64 encoded to produce the string.

**Comment by gfullmer** [comment]
Fantastic.  Looking forward to testing it.

**Comment by gfullmer** [comment]
Were you able to look at my example?  Able to see what the problem was? How is the new build coming?  I was able to restore a couple of   files > blocksize, using emacs's base64-encode function on each of the 32bit hashes the raw HashFile data using a keyboard macro that would select 32 bits do the base64-encode and then put the result in another buffer. Sometimes it didn't work, but was able to figure out the right file by hand.   To concatenate them I used windows native "copy /b <binaryfile> + /b <binaryfile>... <restoredfile>" command.  One problem that got me and I am still addressing is Google drive doesn't allow gross downloads of a whole directory if it is over a certain size (I think > 2 gigs - Mine is about 7), so I have to do it in increments.

Thanks again for all you do.

**Comment by kenkendk** [comment]
The new build is here: http://updates.duplicati.com/preview/duplicati-2.0.0.88_preview_2015-08-24.zip

I have not looked at the example just yet.

**Comment by kenkendk** [comment]
I looked at your files, and can reproduce most of it.

The error message happens because the files are renamed (removed the .aes extension after decrypting). Inside the dindex files, it still points to the .zip.aes dblock files, and that causes the crash.

I have updated the code to handle this case, but I cannot get the error you have at the end where it cannot find any timesets. I also do not understand how you can get the "Downloading file (unknown)". It indicates that the file length is unknown, which is weird, since the file is on the local disk.

I hope the new fixes I have fixes the issue, if not, please reopen.

The output I get is:
```
  Listing remote folder ...
  Downloading file (622 bytes) ...
  Downloading file (733 bytes) ...
  Downloading file (645 bytes) ...
  Downloading file (1,02 KB) ...
Failed to process index file: duplicati-i4e1b2cb2b0234839b3b53b6513d81ec2.dindex.zip => Unexpected number of remote volumes detected: 0!
Failed to process index file: duplicati-i7aa2d20676404ec4923ef317f6df8490.dindex.zip => Unexpected number of remote volumes detected: 0!
Probing 2 candidate blocklist volumes
  Downloading file (275,63 KB) ...
  Downloading file (2,32 KB) ...
```

**Comment by kenkendk** [comment]
New build with the fixes for the restore issue is here:
http://updates.duplicati.com/preview/duplicati-2.0.0.89_preview_2015-08-24.zip

**Comment by gfullmer** [comment]
With 2.0.0.89 still get the same final results as with Fin5. 
![fullscreen capture 8242015 102118 am bmp](https://cloud.githubusercontent.com/assets/1638596/9447885/79e3fe9c-4a4e-11e5-82c6-b54465901621.jpg)
 So I recreated a local repository with no encryption called Fin5LocalNQ with a couple of different files and got the same kind of results, but both look OK in the GUI and I can restore files there!  
![fullscreen capture 8242015 103738 am bmp](https://cloud.githubusercontent.com/assets/1638596/9447962/cc0e89f8-4a4e-11e5-99da-c4b7ce05d009.jpg)
![fullscreen capture 8242015 104116 am bmp](https://cloud.githubusercontent.com/assets/1638596/9447970/d9c86654-4a4e-11e5-9c42-57e686fd452d.jpg)

However, when restoring the files from the command line, I can't do it even when the GUI shows that the Database is OK and is working.  Also, it appears that the "restore" when something is well defined in the GUI is different than "restoring from the target" when it is not, no matter what target type is used.  I will try the Commandline.recoverytool in my next test and let you know how it goes. Where can I find documentation on it?  Thanks again for all you do in making this work.

**Comment by kenkendk** [comment]
Could you send me the database that says "No time or version matched a fileset", then I can compare it to mine to see what is different.

The documentation is built-in, just run it with "help" as the only argument, otherwise you can see it here:
https://github.com/duplicati/duplicati/blob/master/Duplicati/CommandLine/RecoveryTool/help.txt

**Comment by gfullmer** [comment]
Sent you the database for the Fin5LocalNQ which is a zip file of the example above which is not encrypted and a local file.  Thanks again for looking at it. 

Duplicati.CommandLine tool works great, however.  Was able to retrieve my backup.

**Comment by kenkendk** [comment]
For the last one, it appears that you only have two files (dindex files?) in the data folder?

**Comment by gfullmer** [comment]
Yes, that is correct.  Two files.  
Tried the same type of example on a Linux Kubuntu (14.04) machine with the same results.

![duplicatiguionlinux](https://cloud.githubusercontent.com/assets/1638596/9474241/4b0903bc-4b14-11e5-9dfb-2a3b35becaf9.jpg)
![duplicatirestorelinux](https://cloud.githubusercontent.com/assets/1638596/9474252/528166f2-4b14-11e5-9b7c-1d887208cdab.jpg)

Thanks again.

**Comment by kenkendk** [comment]
It looks like it does not find any dlist files in the /home/gfulmer/test folder.
It looks like it only finds a single dindex file in that folder.

Do you have an idea as to why that happens?

**Comment by gfullmer** [comment]
No there is actually a dlist, dindex and dblock zip files in that directory.  I will send it to you if you like:

total 48
-rw-rw-r-- 1 gfullmer gfullmer   726 Aug 25 09:04 duplicati-20150825T160436Z.dlist.zip
-rw-rw-r-- 1 gfullmer gfullmer 38417 Aug 25 09:04 duplicati-bfc050ea64cbc42139888b8f78433fa3f.dblock.zip
-rw-rw-r-- 1 gfullmer gfullmer  1039 Aug 25 09:04 duplicati-i77e7f45c9e4543b3876e9c432115815a.dindex.zip

**Comment by gfullmer** [comment]
I have repeated the Commandline "repair"/"list" sequence a number of times over both Ubuntu and Windows 10 operating systems with the same results ("on time or version matches a fileset"), even when the GUI works fine.

**Comment by thumbar** [comment]
Hi. I have been following this thread a couple of days and am starting to get the hang of Duplicati, loving its encryption and ability to backup to Google, but I am stuck on a problem running 2.0.0.89 after uninstalling 2.0.0.87.

Background: A few days ago I tried out 2.0.0.87 and successfully uploaded an encrypted 300 MB test backup to my Google Drive (1-step authentication only), but was unable to restore it, getting the error that I Googled and found this thread by: "Failed to get list of backup times: No filesets found on remote target".  After several unsuccessful attempts to delete and repair the .sqlite db, I deleted 2.0.0.87, all of its AppData remnants, and the 300 MB test backup on my Google Drive, and then downloaded 2.0.0.89 to start my tests from scratch.

The first sign that something was not quite right was seeing a red error icon (X in a red circle) over the lower right corner of the Duplicati icon that appears in the systray after launching Duplicati.GUI.TrayIcon.exe. Ignoring it initially, I created and scheduled a test backup job to copy a few text files to my Google Drive and it ran to failure, reporting this: "Error while running test 6: Found 3 remote files that are not recorded in local storage, please run repair."

As I had mentioned, I had deleted the earlier 300 MB of test backup files from my Google Drive, and all previous 2.0.0.87 files, including from AppData.  I'm not sure if that was a sufficient cleanup at this point and I'm not sure how to run a .sqlite repair for 2.0.0.89, since I don't have the first 300 MB set of backup files that I think the installation is looking for, so would appreciate any help.

**Comment by gfullmer** [comment]
Make sure that the location of a new db.sqlite is specified in the repair command.  I got this message when it was using the one in AppData\Roaming\Duplicati on the Windows PC or .config/Duplicati on the Linux Mahcine.

Also it is interesting that I am getting these messages on the Linux machine from the GUI:
(Duplicati.GUI.TrayIcon:12170): GLib-CRITICAL **: Source ID 39 was not found when attempting to remove it

Also, even from the GUI when I do a remove local DB and repair local DB I get the "Failed to get list of backup times: No filesets found on the remote target" message even when it is a not encrypted local backup.

**Comment by thumbar** [comment]
Thanks for the tip.  I basically followed the below command template from @kenkendk, but the rebuilt database contained no references to what are now basically ghost files - the freshly reinstalled 2.0.0.89 thinks there are files at some destination URL - files it never backed up, but a previous 2.0.0.87 installation had in fact:

Duplicati.CommandLine.exe repair file://c:\backupdata --dbpath=c:\db.sqlite --no-encryption

**Comment by kenkendk** [comment]
Possibly related issues:
#1415 #1420 #1448

**Comment by kenkendk** [comment]
I have a fix to the restore/repair command, which was tracked in #1448 and confirmed fixed.
It could happen that this fixes the issues described here as well, so I have a new build ready here:
http://updates.duplicati.com/preview/duplicati-2.0.0.90_preview_2015-09-15.zip

**Comment by kenkendk** [comment]
Can we mark this as solved? There has been no new reports of this for a while now.
