### ISSUE TITLE
Onedrive for business help - add to wiki faq

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [duplicati/duplicati#1788]
Hey Guys,

Nice work implementing Onedrive for business. Can you provide some instructions on how to do this with O365? What are the servername  and path on server requirements?

Can that be added to the FAQ?

Also, does Onedrive for Business work with your Linux client?

**Comment by FootStark** [comment]
Hi Phillip, 

the (normal) URL to your Onedrive for business documents folder should be something like:
`https://<tennant>.sharepoint.com/personal/<yourmailaddress>/Documents`
You should see the base path in your browser when you log in. For duplicati, just replace `https:` with `od4b:` and add `Documents` after the final slash.

If you want to use a subfolder to store the backup, just specify it in the path by appending it after `/Documents`. A call with a valid URL for duplicati could be somehting like this:

```Duplicati.CommandLine.exe backup od4b://tennant.sharepoint.com/personal/yourmailaddress/Documents/SubFolder/for/backup --auth-username=yourmailaddress --auth-password=yourO365password --passphrase=YourBackupPassphrase D:\Folder\To\Backup```

For more information on the command line options, try `Duplicati.CommandLine.exe help od4b`

I never tested on Linux with Mono. Duplicati uses the official MS libraries to access SharePoint online. Maybe the lib refuses to work under Linux, but there is a chance. Just try it if you have a suitable environment. 

Good luck!

**Comment by phillip-white-sociomantic** [comment]
Thanks! I got this working on Windows. But it was only working with `tenant-my.sharepoint.com`. The `-my` was required. So the connection string is like `od4b://tenant-my.sharepoint.com:443/personal/firstname_lastname_domain_com/Documents/?auth-username=firstname.lastname.domain&auth-password=password`.

That string works with sub folders too. Under Linux, it is a bit different. I have an error about the ssl hash. Which is fixed by adding the `accept-specified-ssl-hash`. Then i have an error that the web address is not found:

```
Failed to connect: No SharePoint web could be logged in to at path 'https://tenant-my.sharepoint.com:443/personal/firstname_lastname_domain_com/Documents/'. Maybe wrong credentials. Or try using '//' in the path to seperate web from folder path.
```

**Comment by Steini1984** [comment]
Ever figure this one out? Having the same problems, both with the webgui and the cli

**Comment by phillip-white-sociomantic** [comment]
No i never did. It sees the Linux mono package doesn't support it.

**Comment by zappeee** [comment]
Will this be added to the FAQ?
Would be nice to have the GUI information too.

**Comment by PMassicotte** [comment]
I have the same problem under linux (#2062).

>Maybe wrong credentials. Or try using '//' in path to separate web from folder path.

**Comment by cellulosa** [comment]
MacOS Sierra 10.12.2 with Mono 4.6 Service Release 2 (4.6.2.16).

Both GUI and CLI throw the same error:

    Failed to connect: No SharePoint web could be logged in to at path 'https://***-my.sharepoint.com:443/personal/***/Documents/Backup'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.

**Comment by cellulosa** [comment]
Error still persists on `duplicati-2.0.1.49_experimental_2017-02-23` and `MonoFramework-MDK-4.8.0.495.macos10.xamarin.universal`.

In addition, there is now a `cert-sync` error:

    No certificates found, you can install some with one of these commands:
        cert-sync /etc/ssl/certs/ca-certificates.crt #for Debian based systems
        cert-sync /etc/pki/tls/certs/ca-bundle.crt #for RedHat derivatives
    Read more: http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync

**Comment by kenkendk** [comment]
@cellulosa That is a hint that the machine appears to have no trusted SSL certificates installed.

Not sure what to do on MacOS, as I use that and it has working SSL when I install Mono from scratch.

For Debian, you can try with `sudo apt install ca-certificates-mono` which should pull the certificates.
In issue #2062 additional OneDrive issues were fixed with `sudo apt install mono-complete`.

**Comment by cellulosa** [comment]
@kenkendk unfortunately there are no such `ca-certificates-mono` or `mono-complete` package on macos. I have tried installing mono via `brew install mono` as well as via Package (.pkg) but the error remains - it seems certificates aren't included by default. I tried to install the ca-certificates myself:

    cd ~/Desktop
    wget http://curl.haxx.se/download/curl-7.53.1.tar.gz
    tar xzf curl-7.53.1.tar.gz
    cd curl-7.53.1/lib
    ./mk-ca-bundle.pl
    
    cert-sync ~/Desktop/curl-7.53.1/lib/ca-bundle.crt

Unfortunately `cert-sync ` tries to import the certificates to `/usr/share/.mono` but since `macos 10.11` the `/usr` folder [isn't writable](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really) - `/usr/local` should be used instead.

Furthermore, apart from the certificates error, the `Failed to connect: No SharePoint web could be logged in to at path (...)` still prompts. It is for sure strictly related to mono and macos - anybody has any idea on how to solve this?

**Comment by moritzrupp** [comment]
Hey,

I'm using Duplicati 2.0.1.56_canary_2017-04-21 on Windows 10 and I'm seeing exactly the same issue:
`Failed to connect: No SharePoint web could be logged in to at path 'https://*****-my.sharepoint.com/personal/*****/Documents/Backup'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.`

The last time it worked was on Monday, May 8.

Any help is highly appreciated.

**Comment by guimchevalier** [comment]
Same issue for me with 2.0.1.56_canary_2017-04-21 on QNAP 4.3.3
First job running with success form 16 May 0:00 AM to 16 May 0:53 AM (UTC +2 time)
Second job on same account failed at around 16 May 3:30 AM (UTC +2 time)
Other jobs on this acound also failed
Testing connexion is not working any more either (same error message)

Jobs were running good the previous day

Any idea ?

**Comment by zappeee** [comment]
I opened a new issue for a similar issue, https://github.com/duplicati/duplicati/issues/2474

**Comment by guimchevalier** [comment]
Thanks, indeed, same problem. I will update this case with my information.
I will try to reboot and see what's hapening ...

**Comment by zappeee** [comment]
@guimchevalier, usually reopening the application helps for me.

**Comment by Symbiot78** [comment]
same problem here as original Poster..

No SharePoint web could be logged in to at path 

'https://companyname-my.sharepoint.com/personal/onedrivetest_companyname_com/Documents/backup'. Maybe wrong credentials. Or try using '//' in path to separate web from folder path.

**Comment by guimchevalier** [comment]
Did it work previously ?
Did you try to restart Duplicati ?
What's your connection settings in the interface ?
Did you try this option : --integrated-authentication=false

**Comment by derrix060** [comment]
@guimchevalier I tried. Still not working.

**Comment by guimchevalier** [comment]
Connection settings in duplicati interface ?

**Comment by Symbiot78** [comment]
this is me...
![2017-05-27_09-36-27](https://cloud.githubusercontent.com/assets/3314249/26519391/c7b6b04e-42c0-11e7-86f4-0c54131e48d2.jpg)
![2017-05-27_09-37-52](https://cloud.githubusercontent.com/assets/3314249/26519393/c7b87e4c-42c0-11e7-91dc-18f3dc41fb35.jpg)
![2017-05-27_09-40-21](https://cloud.githubusercontent.com/assets/3314249/26519392/c7b71016-42c0-11e7-83d9-f443a78d5480.jpg)

I'm on unix/debian.

**Comment by Symbiot78** [comment]
I don't have the option you mention @guimchevalier .

**Comment by Symbiot78** [comment]
ok, so I actually DID have that option.. so I selected it and removed the enable tick.
Same difference..

If I copy paste the link that duplicati says "doesn't exist" it opens my onedrive4B as expected..

User/pass definetely matches the one I use to login.

**Comment by guimchevalier** [comment]
In my configuration, i don't have "/" before personal.

**Comment by Symbiot78** [comment]
One thing that differs from the solutions I've read here is that when using the webgui I cannot add od4b:// because it automatically adds https:// infront of whatever I type into the url.. so If I type in https://mysite- etc
then it will add https and fail because it cannot resolve http://https://mysite- 
I tried removing the / which didn't help :-|

**Comment by guimchevalier** [comment]
Strange, I've nothing in front of the server address
Can you try to update to the last version ?
https://github.com/duplicati/duplicati/releases

**Comment by Symbiot78** [comment]
I Upgraded to newest version.. 
Now I'd love to write that it works.. but alas... 
Same difference.. :-|

**Comment by Symbiot78** [comment]
I'm gonna try running it in a docker instead... hold on..

**Comment by Symbiot78** [comment]
sigh... same difference..

this is linuxserver/duplicati version :

You are currently running Duplicati - 2.0.1.60_canary_2017-05-23

**Comment by jma89** [comment]
I've been having this same problem. I used Fiddler to see what the handshake looked like and saw this header in the response:

X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.

I'm going now to see if setting the automatically-login flag in the browser makes a difference.

**Comment by jma89** [comment]
So no joy in that, but after a quick trip 'round 'le Goog it seems that SharePoint really likes to see a UserAgent header. Seems like Duplicati only sends 4 headers normally:

`GET https://xxxxxxxxxx-my.sharepoint.com/ HTTP/1.1
X-IDCRL_ACCEPTED: t
Host: xxxxxxxxxx-my.sharepoint.com
Connection: Keep-Alive`

Can somebody do a quick test by forcing a UserAgent header and see if that fixes this for us? (I would but a) I don't have the toolchain setup, and b) time is not quite so plentiful right now. Not that it ever is for anybody else.)

**Comment by samuelcwl** [comment]
I have the same problem with my Macbook - OSX 10.11.6, with 2.0.1.61_experimental_2017-05-30.

**Comment by kenkendk** [comment]
@jma89 Does it need to be a particular `UserAgent` value or can I just use `Duplicati-v2.0.1.61` ?

**Comment by jma89** [comment]
@kenkendk I don't think it matters. From the threads I found they could pass along any value and it would be happy.

FWIW: My backups are suddenly working again today. They were erroring out last night, I then put my computer to sleep, woke it up this morning and the backup succeeded at the next scheduled run. (It normally runs every 4 hours.)

Looking further back in the logs: Looks like it also succeeded once yesterday afternoon, then failed again late in the evening/early morning. Rather strange - This may all be caused by a bug on the SharePoint side of the equation.

**Comment by Bruceforce** [comment]
Hi,

I have the same issue as reporterd in #2474 but since the discussion seems to take place in this issue I'll post it in here. I'm on Debian Jessie with Duplicati - 2.0.1.64_canary_2017-06-02.

I just wanted to add to @jma89 answer, that `systemctl restart duplicati` fixed the issue immediately for me. But a few hours later it appeared again and I had to restart duplicati again. 

I also noted that it takes ~5 minutes for duplicati to realize, that the connection is not working if I click on "Test connection" in the webinterface after the issue occurred. Normally, if I actually enter a wrong path it displays the error message as desribed in #2474 after a few seconds.

**Comment by Sytten** [comment]
I'm on the latest 2.0.3.3_beta_2018-04-02 and it is still not possible to login on linux to onedrive business. Works on OSX though...

**Comment by derrix060** [comment]
I have [one project](https://github.com/derrix060/onedriveClient) to make it work on Linux, but the idea is a little bit different from this project...

**Comment by tygill** [comment]
I didn't see this bug before, but the recently added [`OneDrive v2` backend](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#microsoft-onedrive-v2-microsoft-graph-api) should work on Linux / OSX. Unlike the previous `OneDrive` backend, it works for both personal and 'for business' OneDrive and directly uses the Microsoft Graph REST API (rather than a library) to interact with the service. Since it is based on OAuth, it also supports 2FA and doesn't leave passwords exposed in the UI.

For other SharePoint sites, there is also a new [`SharePoint v2` backend](https://duplicati.readthedocs.io/en/latest/05-storage-providers/#microsoft-sharepoint-v2-microsoft-graph-api) that is based on the same API.

**Comment by Sytten** [comment]
I will give it a try @tygill 
Is it possible to use it from the UI or I must pass through the command line. I didn't see the option in the latest build.

**Comment by tygill** [comment]
The new backends should be fully functional from the UI (though you might need to clear your browser's cache for some things to show up correctly).

**Comment by Sytten** [comment]
Hum yea I found out with I didn't see it, I'm running off the docker image of linuxserver who is still on 2.0.3.3 (and the new backend is in 2.0.3.4). Will wait for the next build friday.

**Comment by Sytten** [comment]
Ok the new backend if connecting but I still can't upload files for some reason @tygill.
It reports success after a couple of retry even though the file is never uploaded.
I switched to the new official docker image so it might be because of right to access the files, I'm investigating.

**Comment by PMassicotte** [comment]
@Sytten Do you mind sharing how you did configure it?

**Comment by PlanetWilson** [comment]
I can't get it to work with the current Docker image either on linux. Is this a known issue?

**Comment by SweAdelpha** [comment]
@PlanetWilson Could you please tell me the exakt command you used to get it to work?

**Comment by PlanetWilson** [comment]
@SweAdelpha once ssh’d Into the docker container I ran:-

mono Duplicati.CommandLine.BackendTool.exe TEST “od4b://mydomain-my.sharepoint.com/personal/something_mydomain_uk/Documents/NASBackup/?auth-username=something%40mydomain.uk&auth-password=mypassword&accept-any-ssl-certificate=true&integrated-authentication=false”

**Comment by SweAdelpha** [comment]
@PlanetWilson Thank you!

Although I did not get that command to work since I think there should be a "CREATEFOLDER" somewhere. Did try the "LIST" command instead and now it works!

Thank you a million times again!

**Comment by PlanetWilson** [comment]
I think you need to create the NASBackup folder manuals in my example thinking about it but running anything seems to kick it into action
