### ISSUE TITLE
All dropdowns are empty

### ISSUE THREAD

**Issue by mircowidmer** [duplicati/duplicati#2479]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Version info
**Duplicati Version:** 2.0.1.57 or 2.0.1.56
**Operating System:** Synology DS 415+
**Backend:**

### Bug description
Dropdowns do not contain options.

### Steps to reproduce
- Try to add a new backup

**Actual result:** All dropdowns are empty (e.g. no options are available)
**Expected result:** It should be possible to select different encryption methods and different storage services.

### Screenshots
![](https://image.ibb.co/kAVeGQ/Screen_Shot_2017_05_17_at_20_40_03.png)
![](https://image.ibb.co/n4xWVk/Screen_Shot_2017_05_17_at_21_04_10.png)

**Comment by mircowidmer** [comment]
I found out what the problem was: The mono framework (on my synology) was not started. After starting the mono framework and opening Duplicati again, the dropdowns were filled. Leaving this comment here for anyone who stumbles upon the same weird behaviour.

**Comment by kenkendk** [comment]
That is strange, because if Mono is down, the UI should show something like "connection lost".
Also, afaik, stopping Mono just stops the XSP module which is not used by Duplicati.
Can you reproduce the problem if you stop the Mono package again?

**Comment by mircowidmer** [comment]
I just stopped the mono service and tried to open Duplicati and it indeed showed me the message that it couldn't connect to the server (which I assume is the mono part). After restarting the Duplicati package too, it didn't start (probably because the mono service was necessary to start Duplicati). So I don't know in what state my setup was when the error with no dropdown values occured.

**Comment by Waliers** [comment]
I have the same issue since the latest DSM (DSM 6.1.2-15132). Reinstalled duplicati and mono (both are started) but the dropdowns are still empy as in mircowidmer's pictures.

**Comment by kenkendk** [comment]
This should be fixed with 36cccd9776c7a554008a94c01e941c9bcb136185

**Comment by gogognome** [comment]
![image](https://user-images.githubusercontent.com/4019324/29748845-9eb26e94-8b1e-11e7-85ee-b90da80cffb1.png)

I got the same problem. I run Duplicati - 2.0.2.1_beta_2017-08-01. Actually, when I went to the about page it said unknown version. The service was still running on my Ubuntu server though. After restarting the service this problem disappeared.

**Comment by progers885** [comment]
Hi I got the same problem with a new DS218+ within the DSM non of the dropdowns work:-
DSM6.2.1-23824 Duplicati - 2.0.3.3_beta_2018-04-02

I thought I may get them to work accessing the interface with a browser so I set a password and allowed remote access only to hit the "not logged in problem https://github.com/duplicati/duplicati/issues/3294" when running the gui in the dsm. To get around this problem I started duplicati in a shell using:-
sudo /volume1/@appstore/Mono/usr/local/bin/mono-sgen /volume1/@appstore/Duplicati/Duplicati.Server.exe --webservice-interface=any --webservice-port=8200 --webservice-password=

I was then able to access the gui from firefox and the dropdowns are now visable, I went back to the DSM duplicati gui and that now showed the selections in the dropdown.

So my guess is that a cache or menu options get created when invoking the commandline or when accessed by an external browser.

**Comment by progers885** [comment]
further update after rebooting the DS218+ the problem returned and just accessing the gui with firefox remotely fixed it again until the next reboot of course

**Comment by progers885** [comment]
Problem still exists of no dropdowns with Duplicati Version 2.0.4.5 and DS218+ 
DSM 6.2.1-23824 Update 6
Mono Version 4.6.2 -0096

**Comment by VennGrayDog** [comment]
Problem still exists when staring duplicati as docker container on Ubuntu 18.04 LTS.
