### ISSUE TITLE
2.0.3.7: FATAL UNHANDLED EXCEPTION: System.IO.IOException: Write fault on path ...

### ISSUE THREAD

**Issue by umgfoin** [duplicati/duplicati#3279]
- [X ] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.3.7
- **Operating system**: CentOS 6.9
- **Backend**: SFTP

## Description

Unhandled exception: Write fault on path /usr/share/duplicati/[Unknown]

## Steps to reproduce

1. Use function "Advanced->Verify files"
2. duplicati crashing

## Debug log

<code>
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Write fault on path /usr/share/duplicati/[Unknown]
  at System.IO.FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count) [0x00077] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00090] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at Duplicati.Library.Utility.Utility.CopyStream (System.IO.Stream source, System.IO.Stream target, System.Boolean tryRewindSource, System.Byte[] buf) [0x0002f] in <5c22135b7083459abdb8767ab6361c3a>:0
  at Duplicati.Library.Utility.Utility.CopyStream (System.IO.Stream source, System.IO.Stream target) [0x00000] in <5c22135b7083459abdb8767ab6361c3a>:0
  at Duplicati.Library.Encryption.GPGEncryption.Runner (System.Object x) [0x00007] in <e9a920c08a254e69b3e84390561f9dce>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <135e7c260ae04ab1a5538976c2d8cf31>:0
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <135e7c260ae04ab1a5538976c2d8cf31>:0
</code>

**Comment by verhoek** [comment]
Do you get this exception almost immediately or after some time? Does this happen with version 2.0.3.6?

**Comment by umgfoin** [comment]
Shortly after starting function "Advanced->Verify files".
Last visible log-line:
<code>
DELETE FROM "Block" WHERE "VolumeID" IN (SELECT "ID" FROM "DelVolSetIds"...
</code>
2.0.3.6 is not affected by this issue, but there are other problems (app-freeze) present in both builds 2.0.3.6 and 2.0.3.7. I'll report this in a separate issue.

**Comment by verhoek** [comment]
I cannot reproduce it.

To simplify debugging, could you run the duplicati commandline equivalent for this job to see if this exception then also occurs? Advanced->Commandline->Test. 
You can try to run it through the Web UI, but it probably doesn't work if your storage URL is a bit complicated.
In that case, copy the commandline code from the Web UI and run it on bash with duplicati.commandline.exe, making sure that you put single quotation marks around the storage url. If it complains about an sqlite file not being found, you need to copy the sqlite file of the original job to filename it tries to find when duplicati.commandline.exe is executed (you find it in ~/.config/duplicati).

**Comment by umgfoin** [comment]
Hi Hendrik,
using the full-cmdline including all options (and starting from the update-directory) I get the following result:
`
mono ./Duplicati.CommandLine.exe test "ssh://[...]
`
`Listing remote folder ...`
`  Downloading file (251,96 MB) ...`
`
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Write fault on path /usr/share/duplicati/updates/2.0.3.7/[Unknown]
  at System.IO.FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count) [0x00077] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00090] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at Duplicati.Library.Utility.Utility.CopyStream (System.IO.Stream source, System.IO.Stream target, System.Boolean tryRewindSource, System.Byte[] buf) [0x0002f] in <5c22135b7083459abdb8767ab6361c3a>:0 
  at Duplicati.Library.Utility.Utility.CopyStream (System.IO.Stream source, System.IO.Stream target) [0x00000] in <5c22135b7083459abdb8767ab6361c3a>:0 
  at Duplicati.Library.Encryption.GPGEncryption.Runner (System.Object x) [0x00007] in <e9a920c08a254e69b3e84390561f9dce>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in <135e7c260ae04ab1a5538976c2d8cf31>:0 
`

**Comment by warwickmm** [comment]
What version of mono are you running?  Not sure if it's related, but a similar sounding [issue](https://bugzilla.xamarin.com/show_bug.cgi?id=32905#c1) was fixed in mono 4.4.0.

**Comment by umgfoin** [comment]
```
[u@h duplicati]# mono --version
Mono JIT compiler version 5.12.0.233 (tarball Tue May  8 09:23:43 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

**Comment by verhoek** [comment]
It's easier to debug knowing that the same problem arises with the commandline tool. Still I could not reproduce it. What are your ssh settings (like ssh key/password), how large is your backup set?

**Comment by umgfoin** [comment]
Backupset "complete"
Last successful run: 05/05/2018 (took 00:00:25)
Next scheduled run: Tomorrow at 1:00 AM
Source: 159,38 GB
Backup: 106,84 GB / 5 Versions

```
ssh://sftp.ftp.com/u/ebackup/test?auth-username=ubackup&auth-password=<secret>&ssh-fingerprint=ssh-des<secret>

--thread-priority=idle
--asynchronous-upload-limit=0
--use-block-cache=true
--backup-name=complete
--dbpath=/u/.config/Duplicati/duplicati_db.sqlite
--encryption-module=gpg
--passphrase=<secret>
--dblock-size=256mb
--keep-versions=5
--auto-cleanup=1
--all-versions=true
--snapshot-policy=off
--restore-permissions=true
--quota-size=90GB
--ssh-fingerprint=ssh-des <secret>
--tempdir=/tmp/duplicati
--hardlink-policy=First
--allow-full-removal=true
--concurrency-block-hashers=6
--exclude-files-attributes=temporary
--disable-module=console-password-input
--exclude=/u/.config/Duplicati/*
--exclude=/proc/*
--exclude=/tmp/*

**Comment by ts678** [comment]
Searching all open and closed issues, there were no other ones with IOException write fault
This was not reproducible in 2018, and much has changed in Duplicati, mono, and CentOS.
The cited `mono` issue is no longer directly available. Is issue still of interest and happening?
