### ISSUE TITLE
Duplicati 2 fails with SQLiteException at startup

### ISSUE THREAD

**Issue by l3d00m** [duplicati/duplicati#3358]
- [x] I have searched open and closed issues for duplicates.

----------------------------------------

## Environment info

- **Duplicati version**: duplicati-2.0.3.3_beta_2018-04-02-x64 (installer name)
- **Operating system**: Windows 10 Version 1803
- **Backend**: ---

## Description

Duplicati 2 failed to launch, i wasn't sure why as i didn't know where the crash logs are. If I try to start the Duplicati.Server.exe manually it throws an SQLIteException (see below).

## Screenshots

![grafik](https://user-images.githubusercontent.com/12055376/44995421-3fd12000-afa3-11e8-8b7c-3503c8a11989.png)

## Debug log

```
PS C:\Program Files\Duplicati 2> .\Duplicati.Server.exe
Ein schwerwiegender Fehler trat in Duplicati auf: System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.Read()
   at Duplicati.Server.Database.Connection.<Read>d__75`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Duplicati.Server.Database.Connection.ReadFromDb[T](Func`2 f, String sql, Object[] args)
   at Duplicati.Server.Database.Connection.GetSettings(Int64 id)
   at Duplicati.Server.Database.ServerSettings.ReloadSettings()
   at Duplicati.Server.Database.Connection..ctor(IDbConnection connection)
   at Duplicati.Server.Program.GetDatabaseConnection(Dictionary`2 commandlineOptions)
   at Duplicati.Server.Program.RealMain(String[] _args)
```

**Comment by Pectojin** [comment]
Hmm, according to [this discussion on the forum](https://forum.duplicati.com/t/database-disk-image-is-malformed/1905/) it's likely to be index corruption within the sqlite database.

There isn't currently any code handling this issue, but [Ingmyv's](https://forum.duplicati.com/t/database-disk-image-is-malformed/1905/22) solution may help you. Alternatively recreating the entire job database should resolve the issue, but it may take a lot of time.

Using an SQLite editor ([DBeaver](https://dbeaver.io/) or [SQLite browser](https://sqlitebrowser.org/)) should allow you to run a test to see if this is also the case for you.

You'll need to lookup the path in the Web UI if you don't know where the job specific DB is. Going to the job -> database -> Local database path should show you the full path.

Then opening it in the editor and running this command in the editor
```
pragma integrity_check;
```

I expect it will take a while and then show a result indicating where the problem is.

**Comment by l3d00m** [comment]
I'm unfortunately not able to do it as it's a bit above my technical skills. I'm also not able to access the web UI to see where the DB is because duplicati does not start at all. Is there a way to completely reset duplicati (creating new backup jobs isn't a problem for me). Reinstalling did not fix my problem

**Comment by Pectojin** [comment]
I believe all user data for Duplicati (Databases and other metadata) will be located in one of these 3:
`C:\Users\[user]\AppData\Local\Duplicati (Windows normal install)`
`C:\Users\[user]\AppData\Roaming\Duplicati (Windows with roaming enabled)`
`C:\Windows\System32\config\systemprofile\AppData\Local\Duplicati (service running as Local System Account)`

So deleting that folder should reset your installation.

**Comment by l3d00m** [comment]
That worked, thank you :)
