### ISSUE TITLE
GUI crashes: illegal path character

### ISSUE THREAD

**Issue by vagabundmw** [duplicati/duplicati#4482]
- [x] I have searched open and closed issues for duplicates.
- [x] I have searched the [forum](https://forum.duplicati.com) for related topics.

----------------------------------------

## Environment info

- **Duplicati version**: 2.0.6.0
- **Operating system**: Windows 10
- **Backend**: WebDAV and SFTP

## Description

In v2.0.6.0 both the command line and the GUI (tray icon) crashes during start.

With v0.2.5 this did not occur. Acutally the installation is quite old, I was running for many years and was just updated via the GUI functionality (download / activate).

## Steps to reproduce

1. Either start GUI
2. or attempt something like `Duplicati.CommandLine test` or `Duplicati.CommandLine system-info`.

The issue does not occur when I just run `Duplicati.CommandLine changelog`.

- **Actual result**: 

A crash with the following exception:

    System.ArgumentException: Illegales Zeichen im Pfad.
    bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
    bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
    bei System.IO.Directory.GetFiles(String path, String searchPattern)
    bei Duplicati.Library.Common.IO.SystemIOWindows.GetFiles(String path, String searchPattern)
    bei Duplicati.Library.Utility.TempFile.RemoveOldApplicationTempFiles(Action`2 errorcallback)
    bei Duplicati.CommandLine.Program.ParseCommandLine(TextWriter outwriter, Action`1 setup, Boolean& verboseErrors, String[] args)
    bei Duplicati.CommandLine.Program.RunCommandLine(TextWriter outwriter, TextWriter errwriter, Action`1 setup, String[] args)

The GUI crashes with a similar message but much longer stack trace. So I've copied the one from the command line tool above.

This is from a German Windows. The message string *"Illegales Zeichen im Pfad"* could be translated as "illegal character in path".

After inspecting the behavior with Sysinternals Process Explorer, I'm quite certain, that the exception happens before Duplicati tries to read the config data base. 

At least consciously I do not use any illegal path names anywhere. The installation dir is just `c:\duplicati2`.

The issue also occurs after I forcefully remove `%AppData%\Duplicati`, i.e., the data base.

- **Expected result**:
Not a crash.

## Debug log

I'm not sure how I could even enable the log in my situation.

**Comment by ts678** [comment]
> With v0.2.5 this did not occur. Acutally the installation is quite old, I was running for many years

I can't find that [release](https://github.com/duplicati/duplicati/releases). Though it's not quite many years old, was this v2.0.5.0-2.0.5.0_experimental_2020-01-03 before?
They both run `RemoveOldApplicationTempFiles`, but there are some differences further down in how paths are handled.
[v2.0.6.0-2.0.6.0_experimental_2021-04-09](https://github.com/duplicati/duplicati/releases/tag/v2.0.6.0-2.0.6.0_experimental_2021-04-09)

> Improved long-path support on Windows

If you `echo %TEMP%`, is it nearly 260 characters, contain any unusual special characters, or not reside on local NTFS drive?

[Unable to start up after upgrade from 2.0.5.108 - to 2.0.5.110 - System.ArgumentException: Illegal characters in path. #4295](https://github.com/duplicati/duplicati/issues/4295)
is a similar issue thought fixed in 2.0.5.112_canary_2021-01-20.

What happens if you give Duplicati a temporary folder that's a very plain and simple local NTFS folder that you make, e.g.

`Duplicati.CommandLine system-info --tempdir=C:\temptest`

This should show your `Tempdir` back to you, and also show a lot of other folders. We both have unusual install locations.
I don't have German Windows, but I'd be surprised if .NET Framework objects to German unless it's not kept in Windows. 
Characters in other filesystems can cause problems. There are Windows-incompatible ways to store non-ASCII characters.

**Comment by vagabundmw** [comment]
> I can't find that release. 

Sorry, I mistyped. You're correct, the previous version was indeed v2.0.5.0-2.0.5.0_experimental_2020-01-03.

> What happens if you give Duplicati a temporary folder that's a very plain and simple local NTFS folder that you make, e.g.

I've checked `%TEMP%` and it points to `t:\temp\hugo`. Alas, changing it to the suggested `C:\temptest` and creating the directory and/or calling with the `--tempdir` argument still crashes.

Also, I retried a fresh "install": unpacked the current release ZIP 2.0.6.0_experimental_2021-04-09. This works fine! 

When comparing with my previous folder, that was incrementally updated over the years, I just realized I have been running a 32 bit build on my 64 bit system. Maybe some file virtualization that kicks in causes the issue...

**Comment by ts678** [comment]
> The installation dir is just c:\duplicati2

> When comparing with my previous folder, that was incrementally updated over the years, I just realized I have been running a 32 bit build on my 64 bit system.

How did you find what build you're running? I just tested duplicati-2.0.5.0_experimental_2020-01-03-x86.msi on 64-bit Windows. 
As expected, it installed into C:\Program Files (x86)\Duplicati 2, and Task Manager `Architecture` column showed x86 when it ran.
Having GUI autoupdate it to 2.0.6.0 worked like its usual not-so-reliable self. Activate button killed it, but manual restart came up.
Duplicati processes are usually paired, and Task Manager `Image Path Name` can show which Duplicati is which. As expected, there initially is the C:\Program Files (x86)\Duplicati 2 one, but this launches the C:\ProgramData\Duplicati\updates\2.0.6.0 updated one.
Changing directories following the same plan, and running `Duplicati.CommandLine system-info` worked and its output included
```
Update folder: C:\ProgramData\Duplicati\updates
Base install folder: C:\Program Files (x86)\Duplicati 2
Version name: "2.0.6.0_experimental_2021-04-09" (2.0.6.0)
Current Version folder C:\ProgramData\Duplicati\updates\2.0.6.0
```

Because of crash, you can't show me your version, but please explain what folders you think have been and are now involved with Duplicati base install and updates over time. If a folder does not have a clear version number, you can look at its `changelog.txt`.

> Also, I retried a fresh "install": unpacked the current release ZIP 2.0.6.0_experimental_2021-04-09. This works fine!

That's excellent news. You'll probably still have two Duplicati processes, but there wouldn't be anything newer than 2.0.6.0 around.
There have sometimes been problems with really old Duplicati as the base install. I don't know how far back your base install goes.

**Comment by Athep** [comment]
> [Unable to start up after upgrade from 2.0.5.108 - to 2.0.5.110 - System.ArgumentException: Illegal characters in path. #4295](https://github.com/duplicati/duplicati/issues/4295)
> is a similar issue thought fixed in 2.0.5.112_canary_2021-01-20.

I still have the same issue.  For me the fix was not working. Can't upgrade from 2.0.5.108.

**Comment by ts678** [comment]
> There have sometimes been problems with really old Duplicati as the base install. I don't know how far back your base install goes.

but because that seems to have been related to the #4295 issue, I'm going to ask you to check either per directions there, or if Duplicati isn't starting at the moment, look in changelog.txt in `Program Files\Duplicati 2`. There are also directions there for testing using a `.zip` file install prior to maybe doing a `.msi` install to replace the old base version (please first note what it is).

**Comment by ts678** [comment]
@Athep commented later in the Arpil 16 2021 day, in the above-linked issue:

> One common factor is that both have very old base install.
I'm going to try an on-the-side install from a .zip file.

> Then I did a install from the .msi as well, and after that also on the 2012 server to. All went good.
As I see it, no reason to dig further in this.

@vagabundmw wrote:

> Acutally the installation is quite old, I was running for many years and was just updated

so I'm still looking for the above request on base install age, if issue is still of some interest.
Or try the reinstall methods. It looks like some very old base installs don't update properly.
